repos:
  - repo: local
    hooks:
      - id: cargo-fmt
        name: cargo fmt
        entry: cargo fmt --check
        language: system
        files: (\.rs|\.?rustfmt\.toml)$
        stages: [pre-commit]
        pass_filenames: false

      - id: cargo-clippy
        name: cargo clippy
        entry: cargo clippy --locked --all-targets --no-deps -- -D warnings
        language: system
        files: \.(rs|toml|lock)$
        stages: [pre-commit]
        pass_filenames: false
