[target.aarch64-unknown-linux-gnu]
pre-build = [
    "apt-get update && apt-get install --assume-yes ca-certificates curl make perl unzip",
    "curl --fail --location --output /tmp/protoc.zip https://github.com/protocolbuffers/protobuf/releases/download/v25.3/protoc-25.3-linux-x86_64.zip",
    "unzip -o /tmp/protoc.zip -d /usr/local",
    "chmod +x /usr/local/bin/protoc",
]
