use super::selection::ScreenPosition;
use super::state::{HelpTab, Overlay, StatusTab};

#[derive(Debug, Clone)]
pub enum AppEvent {
    Noop,
    OpenOverlay(Overlay),
    CloseOverlay,
    SubmitComposer,
    InsertNewline,
    InputChar(char),
    Backspace,
    DeleteForward,
    MoveCursorLeft,
    MoveCursorRight,
    MoveCursorHome,
    MoveCursorEnd,
    MoveCursorUp,
    MoveCursorDown,
    NavigateInputHistory(i32),
    ScrollTranscript(i32),
    StartTranscriptSelection(ScreenPosition),
    DragTranscriptSelection(ScreenPosition),
    FinishTranscriptSelection(ScreenPosition),
    ScrollContext(i32),
    MoveCommandSelection(i32),
    MoveApprovalSelection(i32),
    MovePermissionSelection(i32),
    SetPermissionSelection(usize),
    MoveSkillsSelection(i32),
    /// Generic list-picker move/set events — used by Overlay::ListPicker.
    MoveListPickerSelection(i32),
    SetListPickerSelection(usize),
    ToggleSkillSelection,
    SelectPendingOption(usize),
    CycleModelSelection,
    SaveBaseUrlInput,
    SaveApiKeyInput,
    SaveModelNameInput,
    SaveOpenAiProfileLabelInput,
    CreateOpenAiProfile,
    EditOpenAiProfile,
    DeleteOpenAiProfile,
    RefreshDeepSeekModels,
    SelectHelpTab(HelpTab),
    SelectStatusTab(StatusTab),
    ApplyOverlaySelection,
    CycleResumeSort,
    ClearResumeSearch,
    CancelRunningTask,
    ClearComposer,
    ToggleSidebar,
    ToggleThinking,
}
