[package]
name = "rara-persistence"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
regex = "1"
url = "2"
tempfile.workspace = true
serde = { version = "1", features = ["derive"] }
serde_json.workspace = true
uuid = { version = "1", features = ["v4"] }
