[package]
name = "rara-bedrock"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
aws-config = { version = "1.8.17", features = ["behavior-version-latest"] }
aws-sdk-bedrockruntime = { version = "1.132", features = ["behavior-version-latest"] }
aws-smithy-types = "1.4"
serde_json.workspace = true
